from BaseClasses import World, Item, Location, Region, Entrance
from .items import sekiro_items  # generated by export_items.py
from .locations import sekiro_locations  # generated by csv_to_locations.py
from .options import sekiro_options
from .logic import add_sekiro_logic

class SekiroWorld(World):
    game = "Sekiro"
    topology_present = True
    option_definitions = sekiro_options

    def __init__(self, world, player):
        super().__init__(world, player)
        self.item_name_to_id = {it['name']: it['id'] for it in sekiro_items}

    def create_regions(self):
        # Create simple single-region world (you should expand into many regions)
        region = Region("Ashina Outskirts", self.player, self)
        for loc in sekiro_locations:
            location = Location(loc['name'], loc['address'], region)
            self.locations.append(location)
            region.locations.append(location)

        add_sekiro_logic(self)  # connect regions and set rules

    def create_items(self):
        for it in sekiro_items:
            item = Item(it['name'], it['classification'], it.get('code', 0))
            self.items.append(item)

    def fill_slot_data(self):
        # This determines per-world options sent to clients
        return {}
